apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-directory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      runtimeClassName: fargate
      containers:
      - name: frontend
        image: <your-frontend-image>  # Replace with your actual image URI
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "https://directory.company-internal.com/api"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1024Mi"
