apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: employee-directory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      runtimeClassName: fargate
      containers:
      - name: frontend
        image: <your-frontend-image>
        ports:
        - containerPort: 80
