apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: employee-directory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: ec2-node-group
      containers:
      - name: backend
        image: <your-backend-image>
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
